name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  nix-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Show Nix version
        run: nix --version

      - name: Flake checks
        run: nix flake check --print-build-logs --show-trace --all-systems

      - name: Build scan-build report
        run: nix build --print-build-logs .#checks.x86_64-linux.scan-build

      - name: Upload scan-build HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: scan-build-report
          path: result/scan-report
          if-no-files-found: warn

